/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.tallerjpa.view;

import co.edu.sena.tallerjpa.controller.ArticleController;
import co.edu.sena.tallerjpa.controller.CategoryController;
import co.edu.sena.tallerjpa.controller.IArticleController;
import co.edu.sena.tallerjpa.controller.ICategoryController;
import co.edu.sena.tallerjpa.controller.IPresentationController;
import co.edu.sena.tallerjpa.controller.ISupplierController;
import co.edu.sena.tallerjpa.controller.PresentationController;
import co.edu.sena.tallerjpa.controller.SupplierController;
import co.edu.sena.tallerjpa.model.Article;
import co.edu.sena.tallerjpa.model.Category;
import co.edu.sena.tallerjpa.model.Presentation;
import co.edu.sena.tallerjpa.model.Supplier;
import co.edu.sena.tallerjpa.utils.MessageUtils;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Ortiz
 */
public class JFrameArticle extends javax.swing.JFrame {
    private IArticleController articlecontroller = new ArticleController();
    private IPresentationController presentationController = new PresentationController();
    private ICategoryController categoryController = new CategoryController();
    private ISupplierController supplierController = new SupplierController();
    /**
     * Creates new form JFrameArticle
     */
    public JFrameArticle() {
        initComponents();
        fillTable();
        fillComboIds();
    }
    public void fillComboIds(){
        try {
            List <Presentation> types = presentationController.findAll();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            jComboBoxIdPresentation.setModel(model);
            model.addAll(types);
            DefaultComboBoxModel model2 = new DefaultComboBoxModel();
            List <Category> types2 = categoryController.findAll();
            jComboBoxIdCategory.setModel(model2);
            model2.addAll(types2);
            DefaultComboBoxModel model3 = new DefaultComboBoxModel();
            List <Supplier> types3 = supplierController.findAll();
            jComboBoxIdSupplier.setModel(model3);
            model3.addAll(types3);
        } 
        catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }
    public void fillTable(){
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableArticle.setModel(model);
            model.addColumn("Id");
            model.addColumn("Nombre");
            model.addColumn("Cantidad");
            model.addColumn("URl foto");
            model.addColumn("Ficha tecnica");
            model.addColumn("ID Presentación");
            model.addColumn("ID Categoria");
            model.addColumn("ID Proveedor");
            
            String[] rows = new String[8];
            List <Article> articles = articlecontroller.findAll();
            for (Article article : articles) {
                rows[0] = String.valueOf(article.getIdArticle());
                rows[1] = article.getName();
                rows[2] = String.valueOf(article.getQuantity());
                rows[3] = article.getPhoto();
                rows[4] = article.getTechnicalSheet();
                rows[5] = String.valueOf(article.getIdPresentation());
                rows[6] = String.valueOf(article.getIdCategory());
                rows[7] = String.valueOf(article.getIdSupplier());
                model.addRow(rows);
            }
        } 
        catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticle = new javax.swing.JTable();
        jButtonInsert = new javax.swing.JButton();
        jButtonModify = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jLabelIdArticle = new javax.swing.JLabel();
        jTextFieldIdArticle = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelQuanity = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jLabelPhoto = new javax.swing.JLabel();
        jTextFieldPhoto = new javax.swing.JTextField();
        jLabelTechnicalSheet = new javax.swing.JLabel();
        jTextFieldTechnicalSheet = new javax.swing.JTextField();
        jLabelIdpresentation = new javax.swing.JLabel();
        jComboBoxIdPresentation = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxIdCategory = new javax.swing.JComboBox<>();
        jLabelIdSupplier = new javax.swing.JLabel();
        jComboBoxIdSupplier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(31, 164, 40));
        jPanel2.setToolTipText("");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/tallerjpa/view/Logo_Stock_Clem_100x100_optimized.png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Sena CLEM Tuluá");

        jLabelTitle2.setFont(new java.awt.Font("Arial", 1, 33)); // NOI18N
        jLabelTitle2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle2.setText("Articulo");

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/tallerjpa/view/home.png"))); // NOI18N
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelTitle2)
                    .addComponent(jLabelHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitle)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArticleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArticle);

        jButtonInsert.setBackground(new java.awt.Color(51, 153, 0));
        jButtonInsert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert.setText("Insertar");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonModify.setBackground(new java.awt.Color(51, 102, 255));
        jButtonModify.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonModify.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModify.setText("Modificar");
        jButtonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonClean.setBackground(new java.awt.Color(102, 102, 102));
        jButtonClean.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonClean.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClean.setText("Limpiar");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jLabelIdArticle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelIdArticle.setText("ID:");

        jTextFieldIdArticle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelName.setText("Nombre:");

        jTextFieldName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelQuanity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelQuanity.setText("Cantidad:");

        jTextFieldQuantity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelPhoto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPhoto.setText("URL Foto:");

        jTextFieldPhoto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelTechnicalSheet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTechnicalSheet.setText("Ficha tecnica:");

        jTextFieldTechnicalSheet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelIdpresentation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelIdpresentation.setText("ID presentación:");

        jComboBoxIdPresentation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("ID categoria:");

        jComboBoxIdCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxIdCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabelIdSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelIdSupplier.setText("ID proveedor:");

        jComboBoxIdSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxIdSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIdpresentation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxIdPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxIdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIdSupplier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelIdArticle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIdArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabelQuanity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelPhoto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTechnicalSheet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTechnicalSheet)))
                                .addGap(25, 25, 25))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(jButtonInsert)
                    .addGap(49, 49, 49)
                    .addComponent(jButtonModify)
                    .addGap(64, 64, 64)
                    .addComponent(jButtonDelete)
                    .addGap(64, 64, 64)
                    .addComponent(jButtonClean)
                    .addGap(52, 52, 52)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdArticle)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName)
                    .addComponent(jLabelQuanity)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPhoto)
                        .addComponent(jLabelTechnicalSheet))
                    .addComponent(jTextFieldTechnicalSheet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdpresentation)
                    .addComponent(jComboBoxIdPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxIdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdSupplier)
                    .addComponent(jComboBoxIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(259, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonClean)
                        .addComponent(jButtonDelete)
                        .addComponent(jButtonModify)
                        .addComponent(jButtonInsert))
                    .addGap(136, 136, 136)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        JFrameHome view = new JFrameHome();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jTableArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArticleMouseClicked
        int rowSelected = jTableArticle.getSelectedRow();
        if(rowSelected != -1)
        {
            long idArticleSelected = Long.parseLong(jTableArticle.getValueAt(rowSelected, 0).toString());
            try {
                Article article = articlecontroller.findById(idArticleSelected);
                jTextFieldIdArticle.setText(String.valueOf(idArticleSelected));
                jTextFieldName.setText(article.getName());
                jTextFieldPhoto.setText(article.getPhoto());
                jTextFieldQuantity.setText(String.valueOf(article.getQuantity()));
                jTextFieldTechnicalSheet.setText(article.getTechnicalSheet());
                jComboBoxIdPresentation.getModel().setSelectedItem(article.getIdPresentation());
                jComboBoxIdCategory.getModel().setSelectedItem(article.getIdCategory());
                jComboBoxIdSupplier.getModel().setSelectedItem(article.getIdSupplier());
                
                jButtonInsert.setEnabled(false);
                jButtonDelete.setEnabled(true);
                jButtonModify.setEnabled(true);
            } 
            catch (Exception e) {
                MessageUtils.showErrorMessage(e.getMessage());
            }
        }
    }//GEN-LAST:event_jTableArticleMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        try {
            Article article = new Article();
            article.setIdArticle(Long.parseLong(jTextFieldIdArticle.getText().toUpperCase()));
            article.setName(jTextFieldName.getText().toUpperCase());
            article.setQuantity(Integer.parseInt(jTextFieldQuantity.getText().toUpperCase()));
            article.setPhoto(jTextFieldPhoto.getText().toUpperCase());
            article.setTechnicalSheet(jTextFieldTechnicalSheet.getText().toUpperCase());
            
            //FKs
            Presentation type = (Presentation) jComboBoxIdPresentation.getSelectedItem();
            article.setIdPresentation(type);
            
            Category type2 = (Category) jComboBoxIdCategory.getSelectedItem();
            article.setIdCategory(type2);
            
            Supplier type3 = (Supplier) jComboBoxIdSupplier.getSelectedItem();
            article.setIdSupplier(type3);
            
            articlecontroller.insert(article);
            MessageUtils.showInfoMessage("Articulo Creado exitosamente");
            fillTable();
            clean();
        }
        catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyActionPerformed
        try {
            Article article = new Article();
            article.setIdArticle(Long.parseLong(jTextFieldIdArticle.getText().toUpperCase()));
            article.setName(jTextFieldName.getText().toUpperCase());
            article.setQuantity(Integer.parseInt(jTextFieldQuantity.getText().toUpperCase()));
            article.setPhoto(jTextFieldPhoto.getText().toUpperCase());
            article.setTechnicalSheet(jTextFieldTechnicalSheet.getText().toUpperCase());
            
            //FKs
            Presentation type = (Presentation) jComboBoxIdPresentation.getSelectedItem();
            article.setIdPresentation(type);
            
            Category type2 = (Category) jComboBoxIdCategory.getSelectedItem();
            article.setIdCategory(type2);
            
            Supplier type3 = (Supplier) jComboBoxIdSupplier.getSelectedItem();
            article.setIdSupplier(type3);
            
            articlecontroller.update(article);
            MessageUtils.showInfoMessage("Articulo modificado exitosamente");
            fillTable();
            clean();
        }
        catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonModifyActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            int option = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar esta categoria?",
                "Confirmacion", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION)
            {
                articlecontroller.delete(Long.parseLong(jTextFieldIdArticle.getText()));
                MessageUtils.showInfoMessage("Articulo eliminado exitosamente");
                fillTable();
                clean();
            }

        }
        catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        clean();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    public void clean(){
        jTextFieldIdArticle.setText("");
        jTextFieldName.setText("");
        jTextFieldQuantity.setText("");
        jTextFieldPhoto.setText("");
        jTextFieldTechnicalSheet.setText("");
        jComboBoxIdPresentation.setSelectedIndex(0);
        jComboBoxIdCategory.setSelectedIndex(0);
        jComboBoxIdSupplier.setSelectedIndex(0);
        jTableArticle.clearSelection();
        jButtonInsert.setEnabled(true);
        jButtonModify.setEnabled(false);
        jButtonDelete.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonModify;
    private javax.swing.JComboBox<String> jComboBoxIdCategory;
    private javax.swing.JComboBox<String> jComboBoxIdPresentation;
    private javax.swing.JComboBox<String> jComboBoxIdSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelIdArticle;
    private javax.swing.JLabel jLabelIdSupplier;
    private javax.swing.JLabel jLabelIdpresentation;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelQuanity;
    private javax.swing.JLabel jLabelTechnicalSheet;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArticle;
    private javax.swing.JTextField jTextFieldIdArticle;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoto;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldTechnicalSheet;
    // End of variables declaration//GEN-END:variables
}
